name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: |
        npm install
        npm install -g gulp-cli
     
  build:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
    - uses: actions/checkout@v2
    - run: gulp build
  
  test:
    runs-on: ubuntu-latest
    needs: [install, build]
    steps:
      - uses: actions/checkout@v2
      - run: gulp test
